name: inkin
description: A personal website.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.13
  get_it: ^7.2.0
  google_fonts: ^2.3.2
  rxdart: ^0.27.3
  url_strategy: ^0.2.0

# Our packages:
  app_state: ^0.3.3
  keyed_collection_widgets: ^0.2.0
  model_interfaces: ^0.1.4
  model_fetch: ^0.2.0
  model_fetch_firestore: ^0.2.0
  model_fetch_flutter: ^0.2.0

#  app_state:
#    path: '../../flutter-app-state'
#  model_fetch:
#    path: '../../dart-model-fetch/model_fetch'
#  model_fetch_firestore:
#    path: '../../dart-model-fetch/model_fetch_firestore'
#  model_fetch_flutter:
#    path: '../../dart-model-fetch/model_fetch_flutter'

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
